services:
  - type: web
    name: caloreat-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
